#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Creature()

	result.template = "object/mobile/shared_bearded_jax_hue.iff"
	result.attribute_template_id = 9
	result.stfName("monster_name","bearded_jax")		
	
	#### BEGIN MODIFICATIONS ####
	result.options_mask = 0x100
	result.pvp_status = PVPSTATUS.PvPStatus_None
	result.setStringAttribute("radial_filename", "radials/player_pet.py")
	####  END MODIFICATIONS  ####
	
	return result