#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Tangible()

	result.template = "object/tangible/deed/pet_deed/shared_deed_dz70_basic.iff"
	result.attribute_template_id = 2
	result.stfName("deed","dz70_basic_deed")		
	
	#### BEGIN MODIFICATIONS ####
	result.setStringAttribute("radial_filename", "radials.deed_datapad")
	result.setStringAttribute("deed_pcd", "object/intangible/pet/shared_dz70_fuitive_tracker_droid.iff")
	result.setStringAttribute("deed_mobile", "object/mobile/pet/shared_dz70_fuitive_tracker_droid.iff")
	####  END MODIFICATIONS  ####
	
	return result