#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Tangible()

	result.template = "object/tangible/loot/loot_schematic/shared_death_watch_mandalorian_jetpack_schematic.iff"
	result.attribute_template_id = -1
	result.stfName("craft_item_ingredients_n","mandalorian_jetpack")		
	
	#### BEGIN MODIFICATIONS ####
	####  END MODIFICATIONS  ####
	
	return result