#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = ResourceContainer()

	result.template = "object/resource_container/shared_resource_container_inorganic_water_lg.iff"
	result.attribute_template_id = -1
	result.stfName("resource_container_n","inorganic_water_large")		
	
	#### BEGIN MODIFICATIONS ####
	####  END MODIFICATIONS  ####
	
	return result