#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Tangible()

	result.template = "object/tangible/deed/vehicle_deed/shared_landspeeder_x31_deed.iff"
	result.attribute_template_id = 2
	result.stfName("pet_deed","landspeeder_x31")		
	
	#### BEGIN MODIFICATIONS ####
	result.setStringAttribute("radial_filename", "radials.deed_datapad")
	result.setStringAttribute("deed_result", "object/intangible/vehicle/shared_landspeeder_x31_pcd.iff")
	####  END MODIFICATIONS  ####
	
	return result