#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *

class Template(BaseTemplate):
	name = "object/tangible/wearables/shirt/shared_singing_mountain_clan_shirt_s03.iff"
	is_prototype = False
	
	def create(self, kernel, params):
		result = Tangible()
	
		result.template = "object/tangible/wearables/shirt/shared_singing_mountain_clan_shirt_s03.iff"
		result.attribute_template_id = 11
		result.stfName("wearables_name","singing_mountain_clan_shirt_s01")		
		
		#### BEGIN MODIFICATIONS ####
		result.max_condition = 1000
		####  END MODIFICATIONS  ####
		
		return result

def loadTemplates(addTemplate):
	addTemplate(Template())