#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Installation()

	result.template = "object/installation/mining_liquid/shared_mining_liquid_moisture_harvester.iff"
	result.attribute_template_id = -1
	result.stfName("installation_n","moisture_mine")		
	
	#### BEGIN MODIFICATIONS ####
	####  END MODIFICATIONS  ####
	
	return result