#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Building()

	result.template = "object/building/corellia/shared_skyscraper_corellia_style_01.iff"
	result.attribute_template_id = -1
	result.stfName("building_name","skyscraper_corellia_style_1")		
	
	#### BEGIN MODIFICATIONS ####
	####  END MODIFICATIONS  ####
	
	return result