#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Static()

	result.template = "object/static/structure/naboo/shared_seawall_straight_naboo_theed_style_3.iff"
	result.attribute_template_id = -1
	result.stfName("obj_n","unknown_object")		
	
	#### BEGIN MODIFICATIONS ####
	####  END MODIFICATIONS  ####
	
	return result