# Build the Boost vendor library
set(Boost_SOURCEDIR "${VENDOR_PREFIX}/src/Boost" CACHE PATH "" FORCE)
set(Boost_INCLUDEDIR "${Boost_SOURCEDIR}" CACHE PATH "" FORCE)
set(Boost_LIBRARYDIR "${Boost_SOURCEDIR}/../Boost-build/lib" CACHE PATH "" FORCE)
set(BoostShared_LIBRARYDIR "${Boost_SOURCEDIR}/../BoostShared-build/lib" CACHE PATH "" FORCE)

list(APPEND vendor_args
	"-DBOOST_INCLUDEDIR:PATH=${Boost_INCLUDEDIR}")
list(APPEND vendor_args
	"-DBOOST_LIBRARYDIR:PATH=${Boost_LIBRARYDIR}")
list(APPEND vendor_args
	"-DBoostShared_LIBRARYDIR:PATH=${BoostShared_LIBRARYDIR}")

if(MSVC)
	set(boost_lib_args
		-DLIBPREFIX=lib
	)
else()	
	set(boost_lib_args
	)
endif()

ExternalProject_Add(Boost
	PREFIX ${VENDOR_PREFIX}
	GIT_REPOSITORY https://github.com/anhstudios/boost.git
	GIT_TAG 11ad4dc
	UPDATE_COMMAND ""
	CMAKE_ARGS
		${boost_lib_args}
		-DENABLE_SHARED:BOOL=OFF
		-DENABLE_STATIC:BOOL=ON
		-DENABLE_MULTITHREADED:BOOL=ON
    	-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    	-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${Boost_LIBRARYDIR}
    	-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=${Boost_LIBRARYDIR}
    	-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${Boost_LIBRARYDIR}
    	-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=${Boost_LIBRARYDIR}
    	-DBUILD_EXAMPLES:BOOL=OFF
    	-DBUILD_TESTING:BOOL=OFF
    	-DBUILD_VERSIONED:BOOL=OFF
    	-DINSTALL_VERSIONED:BOOL=OFF
    	-DWITH_MPI:BOOL=OFF
    	-DBUILD_PROJECTS:LIST=date_time^^thread^^regex^^system^^serialization^^program_options^^filesystem
    LIST_SEPARATOR ^^
    INSTALL_COMMAND ""
)

ExternalProject_Add(BoostShared
    DEPENDS Boost
	PREFIX ${VENDOR_PREFIX}
	DOWNLOAD_COMMAND ""
	SOURCE_DIR ${Boost_SOURCEDIR}
	UPDATE_COMMAND ""
	CMAKE_ARGS
		${boost_lib_args}
		-DENABLE_MULTITHREADED:BOOL=ON
    	-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
		-DCMAKE_MODULE_PATH:PATH=${CMAKE_CURRENT_SOURCE_DIR}/cmake
    	-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${BoostShared_LIBRARYDIR}
    	-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=${BoostShared_LIBRARYDIR}
    	-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${BoostShared_LIBRARYDIR}
    	-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=${BoostShared_LIBRARYDIR}
    	-DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}
		-DPYTHON_INCLUDE_PATH=${PYTHON_INCLUDE_DIR}
		-DPYTHON_LIBRARIES=${PYTHON_LIBRARY}
		-DPYTHON_DEBUG_LIBRARIES=${PYTHON_DEBUG_LIBRARY}
		-DBUILD_EXAMPLES:BOOL=OFF
    	-DBUILD_TESTING:BOOL=OFF
    	-DBUILD_VERSIONED:BOOL=OFF
    	-DINSTALL_VERSIONED:BOOL=OFF
    	-DWITH_MPI:BOOL=OFF
		-DENABLE_SHARED:BOOL=ON
		-DENABLE_STATIC:BOOL=OFF
    	-DBUILD_PROJECTS:LIST=python
    INSTALL_COMMAND ""
)
