#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *

class Template(BaseTemplate):
	name = "object/tangible/hopper/crafting_station_hopper/shared_crafting_station_ingredient_hopper_small.iff"
	is_prototype = False
	
	def create(self, params):
		result = Tangible()
	
		result.template = "object/tangible/hopper/crafting_station_hopper/shared_crafting_station_ingredient_hopper_small.iff"
		result.attribute_template_id = -1
		result.stf_name_file = "hopper_small"
		result.stf_name_string = "crafting"
		
		#### BEGIN MODIFICATIONS ####
		####  END MODIFICATIONS  ####
		
		return result

def loadTemplates(addTemplate):
	addTemplate(Template())