#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *	

def create(kernel):
	result = Tangible()

	result.template = "object/tangible/deed/guild_deed/shared_corellia_guild_deed.iff"
	result.attribute_template_id = 2
	result.stfName("deed","corellia_guild_deed")		
	
	#### BEGIN MODIFICATIONS ####
	result.setStringAttribute("radial_filename", "radials/deed_structure.py")
	result.setStringAttribute("deed_building", "object/building/player/shared_player_guildhall_corellia_style_01.iff")
	####  END MODIFICATIONS  ####
	
	return result